apiVersion: v1
kind: Template
metadata:
  name: java-application-template
  annotations:
    openshift.io/display-name: Java Application
    iconClass: fa fa-code
    description: Template to create a Java application (and its pipeline) based on an specific branch.
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${PARAM_APP_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}-pipeline
  spec:
    source:
      type: Git
      sourceSecret:
        name: git-secret
      git:
        uri: https://github.com/redhatcsargentina/openshift-pipelines.git
        ref: master
      contextDir: environments/dev
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: APP_NAME
          value: ${PARAM_APP_NAME}
        - name: IMAGE_NAME
          value: ${PARAM_IMAGE_NAME}
        - name: APP_TEMPLATE_FILE
          value: ${PARAM_APP_TEMPLATE_FILE}
        - name: GIT_REPO
          value: ${PARAM_GIT_REPO}
        - name: GIT_BRANCH
          value: ${PARAM_GIT_BRANCH}
        - name: TAG_VERSION
          value: ${PARAM_TAG_VERSION}
        - name: GIT_SECRET
          value: git-secret  
        - name: BASE_IMAGE
          value: redhat-openjdk18-openshift:1.2
        - name: ARTIFACTS_DIR
          value: ./target
        - name: JENKINS_AGENT
          value: maven
        - name: COMPILE_COMMAND
          value: "mvn package -DskipTests"
        - name: TEST_COMMAND
          value: "mvn test"
        - name: CODE_ANALYSIS_COMMAND
          value: none
        - name: RELEASE_COMMAND
          value: none
        - name: TECH
          value: java
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
      - generic:
          allowEnv: true
          secret: ${PARAM_WEBHOOK_SECRET}
        type: Generic
parameters:
- description: The application name
  displayName: Application Name
  name: PARAM_APP_NAME
  required: true
- description: The image name
  displayName: Image Name
  name: PARAM_IMAGE_NAME
  required: true
- description: The application template file to create the application
  displayName: Application Template File
  name: PARAM_APP_TEMPLATE_FILE
  value: none
  required: true
- description: The Git repository
  displayName: Git Repository
  name: PARAM_GIT_REPO
  required: true
- description: The Git branch
  displayName: Git Branch
  name: PARAM_GIT_BRANCH
  required: true
- description: Tag image with application version
  displayName: Tag Image
  name: PARAM_TAG_VERSION
  value: "false"
  required: true
- description: A secret string used to configure the webhook
  displayName: Webhook Secret
  name: PARAM_WEBHOOK_SECRET
  generate: expression 
  from: "[a-zA-Z0-9]{40}"